#!/bin/bash

set -ex

# install julia 1.3.1 + packages
wget https://julialang-s3.julialang.org/bin/linux/x64/1.3/julia-1.3.1-linux-x86_64.tar.gz -O ~/julia/julia-1.3.1-linux-x86_64.tar.gz
(cd ~/julia; tar -xvzf julia-1.3.1-linux-x86_64.tar.gz)
ln -s ~/julia/julia-1.3.1/bin/julia /usr/bin/julia

# link with
R -e 'library(badr); badr::setup_julia_package(); badr::load_julia_package'
